// <auto-generated />
using System;
using EFCorePart2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCorePart2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCorePart2.Models.Course", b =>
                {
                    b.Property<int>("Course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Course_id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("course_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.HasKey("Course_id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("EFCorePart2.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("EFCorePart2.Models.Enrolls", b =>
                {
                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.HasKey("S_id", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("Enrolls");
                });

            modelBuilder.Entity("EFCorePart2.Models.Exam", b =>
                {
                    b.Property<int>("ExamCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamCode"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamCode");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("EFCorePart2.Models.Faculity", b =>
                {
                    b.Property<int>("F_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Mobile_no")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("F_id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Faculity");
                });

            modelBuilder.Entity("EFCorePart2.Models.Hostel", b =>
                {
                    b.Property<int>("HostelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostelId"));

                    b.Property<string>("HostelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nomberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("pinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HostelId");

                    b.ToTable("Hostel");
                });

            modelBuilder.Entity("EFCorePart2.Models.Student", b =>
                {
                    b.Property<int>("S_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_id"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HostelId")
                        .HasColumnType("int");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phone_number")
                        .HasColumnType("int");

                    b.HasKey("S_id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HostelId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("EFCorePart2.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("EFCorePart2.Models.Takes", b =>
                {
                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.Property<int>("ExamCode")
                        .HasColumnType("int");

                    b.HasKey("S_id", "ExamCode");

                    b.HasIndex("ExamCode");

                    b.ToTable("Takes");
                });

            modelBuilder.Entity("EFCorePart2.Models.TeachesSubject", b =>
                {
                    b.Property<int>("F_id")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("F_id", "SubjectID", "S_id");

                    b.HasIndex("S_id");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeachesSubject");
                });

            modelBuilder.Entity("EFCorePart2.Models.Course", b =>
                {
                    b.HasOne("EFCorePart2.Models.Department", "Department")
                        .WithMany("Course")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCorePart2.Models.Enrolls", b =>
                {
                    b.HasOne("EFCorePart2.Models.Course", "Course")
                        .WithMany("Enrolls")
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePart2.Models.Student", "Student")
                        .WithMany("Enrolls")
                        .HasForeignKey("S_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCorePart2.Models.Exam", b =>
                {
                    b.HasOne("EFCorePart2.Models.Department", "Department")
                        .WithMany("Exam")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCorePart2.Models.Faculity", b =>
                {
                    b.HasOne("EFCorePart2.Models.Department", "Department")
                        .WithMany("Faculty")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCorePart2.Models.Student", b =>
                {
                    b.HasOne("EFCorePart2.Models.Department", "Department")
                        .WithMany("Student")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePart2.Models.Hostel", "Hostel")
                        .WithMany("Student")
                        .HasForeignKey("HostelId");

                    b.Navigation("Department");

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("EFCorePart2.Models.Takes", b =>
                {
                    b.HasOne("EFCorePart2.Models.Exam", "Exam")
                        .WithMany("Takes")
                        .HasForeignKey("ExamCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePart2.Models.Student", "Student")
                        .WithMany("Takes")
                        .HasForeignKey("S_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCorePart2.Models.TeachesSubject", b =>
                {
                    b.HasOne("EFCorePart2.Models.Faculity", "Faculity")
                        .WithMany("TeachesSubjects")
                        .HasForeignKey("F_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePart2.Models.Student", "Student")
                        .WithMany("TeachesSubjects")
                        .HasForeignKey("S_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePart2.Models.Subject", "Subject")
                        .WithMany("TeachesSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculity");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EFCorePart2.Models.Course", b =>
                {
                    b.Navigation("Enrolls");
                });

            modelBuilder.Entity("EFCorePart2.Models.Department", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("Exam");

                    b.Navigation("Faculty");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCorePart2.Models.Exam", b =>
                {
                    b.Navigation("Takes");
                });

            modelBuilder.Entity("EFCorePart2.Models.Faculity", b =>
                {
                    b.Navigation("TeachesSubjects");
                });

            modelBuilder.Entity("EFCorePart2.Models.Hostel", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCorePart2.Models.Student", b =>
                {
                    b.Navigation("Enrolls");

                    b.Navigation("Takes");

                    b.Navigation("TeachesSubjects");
                });

            modelBuilder.Entity("EFCorePart2.Models.Subject", b =>
                {
                    b.Navigation("TeachesSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
